MAZE = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP           XX            X",
    "X XXXX XXXXX XX XXXXX XXXX X",
    "X XXXXOXXXXX XX XXXXXOXXXX X",
    "X XXXX XXXXX XX XXXXX XXXX X",
    "X                          X",
    "X XXXX XX XXXXXXXX XX XXXX X",
    "X XXXX XX XXXXXXXX XX XXXX X",
    "X      XX    XX    XX      X",
    "XXXXXX XXXXX XX XXXXX XXXXXX",
    "XXXXXX XXXXX XX XXXXX XXXXXX",
    "XXXXXX XX     G    XX XXXXXX",
    "XXXXXX XX XXX  XXX XX XXXXXX",
    "XXXXXX XX X      X XX XXXXXX",
    "   G      X      X          ",
    "XXXXXX XX X      X XX XXXXXX",
    "XXXXXX XX XXXXXXXX XX XXXXXX",
    "XXXXXX XX    G     XX XXXXXX",
    "XXXXXX XX XXXXXXXX XX XXXXXX",
    "XXXXXX XX XXXXXXXX XX XXXXXX",
    "X            XX            X",
    "X XXXX XXXXX XX XXXXX XXXX X",
    "X XXXX XXXXX XX XXXXX XXXX X",
    "X   XX       G        XX   X",
    "XXX XX XX XXXXXXXX XX XX XXX",
    "XXX XX XX XXXXXXXX XX XX XXX",
    "X      XX    XX    XX      X",
    "X XXXXXXXXXX XX XXXXXXXXXX X",
    "X XXXXXXXXXX XX XXXXXXXXXX X",
    "X   O                 O    X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]

SCALE_FACTOR = 3
TILE_SIZE = 8 * SCALE_FACTOR
MAZE_WIDTH = len(MAZE[0])
MAZE_HEIGHT = len(MAZE)
TILE_HALF = int(TILE_SIZE / 2)
APPLE_SIZE = int(TILE_SIZE / 6)
GHOST_SIZE = int(TILE_SIZE * (3 / 4))
HERO_SIZE = int(TILE_SIZE)
POWERUP_SIZE = int(TILE_SIZE / 4)
SCREEN_WIDTH = MAZE_WIDTH * TILE_SIZE
SCREEN_HEIGHT = MAZE_HEIGHT * TILE_SIZE